### ISSUE TITLE
error from npm run dev-reinit

### ISSUE THREAD

**Issue by johnfelipe** [XRFoundation/XREngine#6243]
> xrengine@0.0.0 dev-reinit
	> cd packages/server && npm run dev-reinit-db

	> @xrengine/server@0.5.6 dev-reinit-db
	> cross-env FORCE_DB_REFRESH=true ts-node --transpile-only src/index.ts

	[1653773223764] INFO (25799 on ubuntu21): Starting app.
		component: "server-core:sequelize"
	[1653773224329] INFO (25799 on ubuntu21): Starting server with NO HTTPS, if you meant to use HTTPS try 'sudo bash generate-certs'
		component: "server-core:user"
	[1653773224408] ERROR (25799 on ubuntu21): Sequelize setup error
		component: "server-core:sequelize"
	(node:25799) UnhandledPromiseRejectionWarning
	[ Stacktrace altered by https://github.com/grantila/trace-unhandled ]
	Unknown error
		==== Promise at: ==================
		at Promise.then (<anonymous>)
		at new Project (/root/XREngine/packages/server-core/src/projects/project/project.class.ts:108:22)
		at Function.exports.default (/root/XREngine/packages/server-core/src/projects/project/project.service.ts:30:24)
		at Function.configure (/root/XREngine/node_modules/@feathersjs/feathers/src/application.ts:51:14)
		at /root/XREngine/packages/server-core/src/services.ts:57:9
		at Array.forEach (<anonymous>)
		at Function.exports.default (/root/XREngine/packages/server-core/src/services.ts:56:5)
		at Function.configure (/root/XREngine/node_modules/@feathersjs/feathers/src/application.ts:51:14)
		at createFeathersExpressApp (/root/XREngine/packages/server-core/src/createApp.ts:159:7)
		at start (/root/XREngine/packages/server/src/start.ts:21:39)
		at init (/root/XREngine/packages/server/src/index.ts:6:3)
		at processTicksAndRejections (node:internal/process/task_queues:96:5)

		==== Error at: ====================

		==== Shared trace: ================

	[1653773224409] ERROR (25799 on ubuntu21): Access denied for user ''@'172.18.0.1' (using password: NO)
		component: "server-core:sequelize"
		err: {
		  "type": "AccessDeniedError",
		  "message": "Access denied for user ''@'172.18.0.1' (using password: NO)",
		  "stack":
			  SequelizeAccessDeniedError: Access denied for user ''@'172.18.0.1' (using password: NO)
				  at ConnectionManager.connect (/root/XREngine/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:118:17)
				  at processTicksAndRejections (node:internal/process/task_queues:96:5)
				  at async ConnectionManager._connect (/root/XREngine/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
				  at async /root/XREngine/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
				  at async ConnectionManager.getConnection (/root/XREngine/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
				  at async /root/XREngine/node_modules/sequelize/lib/sequelize.js:631:26
				  at async Function.app.setup (/root/XREngine/packages/server-core/src/sequelize.ts:37:9)
				  at async Function.listen (/root/XREngine/node_modules/@feathersjs/express/src/index.ts:79:7)
				  at async start (/root/XREngine/packages/server/src/start.ts:86:93)
		  "name": "SequelizeAccessDeniedError",
		  "parent": {
			"type": "Error",
			"message": "Access denied for user ''@'172.18.0.1' (using password: NO)",
			"stack":
				Error: Access denied for user ''@'172.18.0.1' (using password: NO)
					at Packet.asError (/root/XREngine/node_modules/mysql2/lib/packets/packet.js:728:17)
					at ClientHandshake.execute (/root/XREngine/node_modules/mysql2/lib/commands/command.js:29:26)
					at Connection.handlePacket (/root/XREngine/node_modules/mysql2/lib/connection.js:456:32)
					at PacketParser.onPacket (/root/XREngine/node_modules/mysql2/lib/connection.js:85:12)
					at PacketParser.executeStart (/root/XREngine/node_modules/mysql2/lib/packet_parser.js:75:16)
					at Socket.<anonymous> (/root/XREngine/node_modules/mysql2/lib/connection.js:92:25)
					at Socket.emit (node:events:527:28)
					at Socket.emit (node:domain:475:12)
					at addChunk (node:internal/streams/readable:315:12)
					at readableAddChunk (node:internal/streams/readable:289:9)
					at Socket.Readable.push (node:internal/streams/readable:228:10)
					at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
			"code": "ER_ACCESS_DENIED_ERROR",
			"errno": 1045,
			"sqlState": "28000",
			"sqlMessage": "Access denied for user ''@'172.18.0.1' (using password: NO)"
		  },
		  "original": {
			"type": "Error",
			"message": "Access denied for user ''@'172.18.0.1' (using password: NO)",
			"stack":
				Error: Access denied for user ''@'172.18.0.1' (using password: NO)
					at Packet.asError (/root/XREngine/node_modules/mysql2/lib/packets/packet.js:728:17)
					at ClientHandshake.execute (/root/XREngine/node_modules/mysql2/lib/commands/command.js:29:26)
					at Connection.handlePacket (/root/XREngine/node_modules/mysql2/lib/connection.js:456:32)
					at PacketParser.onPacket (/root/XREngine/node_modules/mysql2/lib/connection.js:85:12)
					at PacketParser.executeStart (/root/XREngine/node_modules/mysql2/lib/packet_parser.js:75:16)
					at Socket.<anonymous> (/root/XREngine/node_modules/mysql2/lib/connection.js:92:25)
					at Socket.emit (node:events:527:28)
					at Socket.emit (node:domain:475:12)
					at addChunk (node:internal/streams/readable:315:12)
					at readableAddChunk (node:internal/streams/readable:289:9)
					at Socket.Readable.push (node:internal/streams/readable:228:10)
					at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
			"code": "ER_ACCESS_DENIED_ERROR",
			"errno": 1045,
			"sqlState": "28000",
			"sqlMessage": "Access denied for user ''@'172.18.0.1' (using password: NO)"
		  }
		}
	[1653773224430] FATAL (25799 on ubuntu21): UNHANDLED PROMISE REJECTION.
		component: "server-core:config"
		promise: {
		  "__tracedError": {}
		}
	npm ERR! Lifecycle script `dev-reinit-db` failed with error:
	npm ERR! Error: command failed
	npm ERR!   in workspace: @xrengine/server@0.5.6
	npm ERR!   at location: /root/XREngine/packages/server

how solve it?

**Comment by johnfelipe** [comment]
solved
